### ISSUE TITLE
turbografx-16 folder name should be tg16

### ISSUE THREAD

**Issue by msheehan79** [lilbud/es-theme-switch-light#1]
Very nice theme!

Just a minor fix here, but users who want to see the TurboGrafx-16 logo instead of PC Engine and follow RetroPie's docs to add a custom "platforms.cfg" file with the override below will have the theme looking for a folder named "tg16" and not "turbografx16".

pcengine_theme="tg16"
pcengine_platform="tg16"

**Comment by lilbud** [comment]
Fixed it

**Comment by msheehan79** [comment]
Nice! Don't forget to also move the system.png image file into the new folder too.

**Comment by lilbud** [comment]
Done and done
